MVC/MyGameStore/GameStoreMVC/Models/ErrorViewModel.cs
using System;

namespace GameStoreMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/MyGameStore/GameStoreMVC/Controllers/HomeController.cs
using GameStoreMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace GameStoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/MyGameStore/GameStoreMVC/Controllers/PeopleController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyGameStore.BLL.Interfaces;
using MyGameStore.DAL;

namespace GameStoreMVC.Controllers
{
    public class PeopleController : Controller
    {
        private IPerson _service;

        public PeopleController(IPerson context)
        {
            _service = context;
        }
        public IActionResult Index()
        {
            return View(_service.GetAll());
        }
        public IActionResult Delete(int id)
        {
            try
            {
                _service.Delete(id);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
            
            return RedirectToAction("Index");
        }

        public IActionResult GetById(int id)
        {
            Person person = _service.GetbyId(id);
            if (person == null)
                return NotFound("Person not found");
            return View(person);
        }

        public IActionResult Create()
        {
            return View();
        }
       
        [HttpPost]
        public IActionResult Create(Person person)
        {
            try
            {
                _service.Add(person);
            }
            catch (Exception e)
            {
                return NotFound(e.Message);
            }
            
            return RedirectToAction("GetById",person);
        }

        public IActionResult Update(int id)
        {
            Person person = _service.GetbyId(id);
            if(person == null)
                return NotFound("Person not found");
            return View(person);
        }

        [HttpPost]
        public IActionResult Update(Person person)
        {

            _service.Update(person);
            return RedirectToAction("GetById",person);
        }
    }
}

MVC/MyGameStore/GameStoreMVC/Controllers/StoresController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MyGameStore.BLL.Interfaces;
using MyGameStore.DAL;
using MyGameStore.DAL.Repositories;

namespace GameStoreMVC.Controllers
{
    public class StoresController : Controller
    {
        private IStore _service;

        public StoresController(IStore context)
        {
            _service = context;
        }
        public IActionResult Index()
        {
            return View(_service.GetAll(Sort.Ascending, SortBy.Name,"","",1,100).OrderBy(x => x.Id));
        }

        public IActionResult GetById(int id)
        {
            return View(_service.GetbyId(id));
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Update(int id)
        {
            return View(_service.GetAll(Sort.Ascending, SortBy.Name, "", "", 1, 100).First(x => x.Id == id));
        }

        [HttpPost]
        public IActionResult Update(Store store)
        {

            _service.Update(store);
            return RedirectToAction("GetById", store);
        }
        [HttpPost]
        public IActionResult Create(Store store)
        {
            _service.Add(store);
            return RedirectToAction("GetById", store);
        }

        public IActionResult Delete(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MVC/MyGameStore/GameStoreMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC/MyGameStore/GameStoreMVC/Views/People/Create.cshtml
@model MyGameStore.DAL.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
	        <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <input asp-for="StoreId" class="form-control" />
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVC/MyGameStore/GameStoreMVC/Views/People/GetById.cshtml
@model MyGameStore.DAL.Person

@{
    ViewData["Title"] = "GetById";
}

<h1>GetById</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StoreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StoreId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Update", new {  id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

MVC/MyGameStore/GameStoreMVC/Views/People/Index.cshtml
@model IEnumerable<MyGameStore.DAL.Person>

@{
	ViewData["Title"] = "Index";
}
<h1>Get</h1>

<p>
	<a asp-action="Create" asp-controller="People" >Create New</a>
</p>
<table class="table table-bordered table-hover">
	<thead class="thead-dark">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Id)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.LastName)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.StoreId)
		</th>
		<th></th>
	</tr>
	</thead>
	<tbody>
	@foreach (var item in Model) {
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.Id)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.FirstName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.StoreId)
			</td>
			<td>
				@Html.ActionLink("Edit", "Update", new { id=item.Id  }) |
				@Html.ActionLink("Details", "GetById", new {  id=item.Id }) |
				@Html.ActionLink("Delete", "Delete", new { id=item.Id })
			</td>
		</tr>
	}
	</tbody>
</table>

MVC/MyGameStore/GameStoreMVC/Views/People/Update.cshtml
@model MyGameStore.DAL.Person

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled"  />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoreId" class="control-label"></label>
                <input asp-for="StoreId" class="form-control" />
                <span asp-validation-for="StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVC/MyGameStore/GameStoreMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GameStoreMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
	                    </li>
	                    <li class="nav-item">
		                    <a class="nav-link text-dark" asp-area="" asp-controller="Stores" asp-action="Index">Stores</a>
	                    </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GameStoreMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC/MyGameStore/GameStoreMVC/Views/Stores/Create.cshtml
@model MyGameStore.DAL.Store

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Store</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
	        <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Addition" class="control-label"></label>
                <input asp-for="Addition" class="form-control" />
                <span asp-validation-for="Addition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFranchiseStore" /> @Html.DisplayNameFor(model => model.IsFranchiseStore)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVC/MyGameStore/GameStoreMVC/Views/Stores/GetById.cshtml
@model MyGameStore.DAL.Store

@{
    ViewData["Title"] = "GetById";
}

<h1>GetById</h1>

<div>
    <h4>Store</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Addition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Addition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ZipCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFranchiseStore)
        </dt>
        <dd class = "col-sm-10">
	        <p> @(Model.IsFranchiseStore?"Yes":"No") </p>
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Update", new { id = Model.Id}) |
    <a asp-action="Index">Back to List</a>
</div>

MVC/MyGameStore/GameStoreMVC/Views/Stores/Index.cshtml
@model IEnumerable<MyGameStore.DAL.Store>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ZipCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
	        <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => item.Id)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Name)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Street)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Number)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Addition)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.ZipCode)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.City)
		</td>
		<td>
			@Html.ActionLink("Edit", "Update", new { id = item.Id }) |
			@Html.ActionLink("Details", "GetById", new { id = item.Id }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.Id })
		</td>
	</tr>
}
    </tbody>
</table>

MVC/MyGameStore/GameStoreMVC/Views/Stores/Update.cshtml
@model MyGameStore.DAL.Store

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>Store</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled"/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Addition" class="control-label"></label>
                <input asp-for="Addition" class="form-control" />
                <span asp-validation-for="Addition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ZipCode" class="control-label"></label>
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFranchiseStore" /> @Html.DisplayNameFor(model => model.IsFranchiseStore)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>